name: CrystalSMP
main: me.Chookoo.testPlugin.Main
version: 1.0
api-version: 1.21
commands:
  ability:
    description: Use your abilities
    usage: /ability <copper|gold|iron|lapis|redstone|emerald> <level>
